### ISSUE TITLE
[Feature] Better customizations over kit lores

### ISSUE THREAD

**Issue by benjaminforras** [TryHardDood/AdvancedKitsReloaded#4]
In the config.yml will contain this:
```
display:
  unlocked:
    when_bought: true
    when_unlocked: true
    when_admin: true
  cost:
    when_bought: true
    when_unlocked: true
    when_admin: true
  delay:
    when_bought: true
    when_unlocked: true
    when_admin: true
  permission:
    when_bought: true
    when_unlocked: true
    when_admin: true
  disabledworlds:
    when_bought: true
    when_unlocked: true
    when_admin: true
```

**when_bought**: After a player buys a kit won't see this lore.
**when_bought**: After a player unlocks a kit won't see this lore.
**when_admin**: If a player is an admin will see the lore even if it's turned off.
